apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: defaultapplication
  name: defaultapplication
spec:
  path:
    /
  port:
    targetPort: http
  to:
    kind: Service
    name: defaultapplication
    weight: 100
