apiVersion: v1
kind: Service
metadata:
  labels:
    app: defaultapplication
  name: defaultapplication
spec:
  type: NodePort
  ports:
    - name: http
      port: 9080
      targetPort: 9080
  selector:
    app: defaultapplication
